name: CI - feature to Develope

on:
  pull_request:
    branches: [Develop, main]
  push:
    branches: [Develop, main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: os-${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            os-${{runner.os}}-node-

      - name: Change node version
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      
      # INSTALL DEPENDENCIES
      - name: Install npm
        run: |
          cd react-app
          npm ci

      # - name: Check code format
      #   run: |
      #     cd react-app
      #     npm run format:check

      - name: Test code and check coverage
        run: |
          cd react-app
          npm test -- --coverage
        env:
          CI: true
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: react-app/coverage


      - name: Build project
        if: github.event_name == 'push'
        run: |
          cd react-app
          npm run build
          
      - name: Upload Build folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: react-app/build
          
      - name: Deploy on staging
        if: github.event_name == 'push'
        run: |
          cd react-app
          npx surge --project ./build --domain http://elite-kno100t.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

      - name: Create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/cache_feat'

        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
