name: Simple shell commands workflows

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello from Github Actions!"
        # To make the Job fail, we can change the echo command to a typo
        # for example: eccho "Hello"
      - name: multiline commands
        run: |
          node -v
          npm -v
