name: Add files to repo with the workflow

on: push

jobs:

  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: push random file
        # git remote add origin "git@github.com:${GITHUB_REPOSITORY}.git"
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m"Random file"
          git push
